### ISSUE TITLE
Trouble setting up the gem for local development

### ISSUE THREAD

**Issue by dqdinh** [lookout/fast-rsa-engine#25]
@mkristian -- I'm running to trouble trying to develop this gem locally. I'm trying to get this gem to work on jruby-9170.

Following the README development instructions (https://github.com/lookout/fast-rsa-engine#developement) results in a strange gemspec error. I think `bundle install` is not generating the `lib/fast-rsa-engine.jar` which the gemspec file expects (https://github.com/lookout/fast-rsa-engine/blob/master/fast-rsa-engine.gemspec#L17).

Here's the error: 
```
$ bundle exec rake --trace
** Invoke default (first_time)
** Invoke jar (first_time)
** Execute jar
rake aborted!
vendor dir  not in require_paths of gemspec ["lib"]
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/jar-dependencies-0.3.9/lib/jars/installer.rb:212:in `do_install'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/jar-dependencies-0.3.9/lib/jars/installer.rb:186:in `install_jars'
/Users/ddinh/workspace/lookout/fast-rsa-engine/Rakefile:10:in `(root)'
org/jruby/RubyProc.java:281:in `call'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/task.rb:240:in `execute'
org/jruby/RubyArray.java:1613:in `each'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/task.rb:179:in `invoke_with_call_chain'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/task.rb:201:in `invoke_prerequisites'
org/jruby/RubyArray.java:1613:in `each'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/task.rb:178:in `invoke_with_call_chain'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/application.rb:106:in `top_level'
org/jruby/RubyArray.java:1613:in `each'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/application.rb:106:in `top_level'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/application.rb:78:in `run'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/lib/ruby/gems/shared/gems/rake-10.5.0/bin/rake:33:in `(root)'
org/jruby/RubyKernel.java:1059:in `load'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/bin/rake:1:in `(root)'
org/jruby/RubyKernel.java:1079:in `eval'
/Users/ddinh/.rbenv/versions/jruby-1.7.25/bin/jruby_executable_hooks:15:in `(root)'
Tasks: TOP => default => jar
```

Any advice?

Thanks!

**Comment by dqdinh** [comment]
Below is more info about my local dev environment. It is more recent than what I see in the most recent Travis CI run -- https://travis-ci.org/lookout/fast-rsa-engine/jobs/80679642

I'll try to match the ruby, bundler, and gem version that are shown in Travis.

```
$ java -Xmx32m -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)
```

```
$ ruby --version
jruby 1.7.25 (1.9.3p551) 2016-04-13 867cb81 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_112-b16 +jit [darwin-x86_64]
```

```
$ bundle --version
Bundler version 1.14.3
```

```
$ gem --version
2.4.8
```

**Comment by dqdinh** [comment]
Figured it out. I needed required jars in `lib/com`

```
$ ls lib/com/squareup/jnagmp/
bouncycastle-rsa jnagmp
```

which is what `get all the gems and jars in place` implied in the README.

**Comment by dqdinh** [comment]
So the issue is that the development flow breaks with the latest versin of jar-dependencies (0.3.9). It works with 0.2.2.

**Comment by dqdinh** [comment]
I isolated the issue by going from jar-dependency version 0.3.9 -> 0.3.2 and pinning it.

https://github.com/lookout/fast-rsa-engine/pull/27
