### ISSUE TITLE
JRuby 9.1.7.0 compatibility 

### ISSUE THREAD

**Issue by dqdinh** [lookout/fast-rsa-engine#28]
Hi @mkristian, I want to install fast-rsa-engine with JRuby 9.1.7.0 but running into the following error below.

I'm assuming the problem is with ruby-maven and JRuby 9.1.7.0 incompatibility.

What versions of JRuby does ruby-maven support?

I tried to check the .travis.yml file (https://github.com/takari/ruby-maven/blob/master/.travis.yml#L6) and it says `jruby-head` but it does not look like @takari is running travis-ci checks (https://travis-ci.org/takari)

I also tried to check https://travis-ci.org/mkristian/ruby-maven/builds but it only had old builds.

```
$ gem install fast-rsa-engine -v '0.3.2' --backtrace
  jar dependencies for fast-rsa-engine-0.3.2-java.gemspec . . .
ERROR:  While executing gem ... (NoMethodError)
    private method `exec' called for Maven:Module
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/ruby-maven-3.3.12/lib/ruby_maven.rb:77:in `launch'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/ruby-maven-3.3.12/lib/ruby_maven.rb:42:in `exec'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/ruby-maven-3.3.12/lib/maven/ruby/maven.rb:112:in `exec'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/jars/maven_exec.rb:79:in `resolve_dependencies_list'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/jars/installer.rb:237:in `install_dependencies'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/jars/installer.rb:226:in `do_install'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/jars/installer.rb:172:in `vendor_jars'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/jars/post_install_hook.rb:28:in `block in (root)'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/rubygems/installer.rb:353:in `block in run_post_install_hooks'
	org/jruby/RubyArray.java:1733:in `each'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/rubygems/installer.rb:352:in `run_post_install_hooks'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/rubygems/installer.rb:317:in `install'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/rubygems/resolver/specification.rb:97:in `install'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/rubygems/request_set.rb:166:in `block in install'
	org/jruby/RubyArray.java:1733:in `each'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/rubygems/request_set.rb:156:in `install'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/rubygems/commands/install_command.rb:205:in `install_gem'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/rubygems/commands/install_command.rb:255:in `block in install_gems'
	org/jruby/RubyArray.java:1733:in `each'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/rubygems/commands/install_command.rb:251:in `install_gems'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/rubygems/commands/install_command.rb:158:in `execute'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/rubygems/command.rb:310:in `invoke_with_build_args'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/rubygems/command_manager.rb:169:in `process_args'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/rubygems/command_manager.rb:139:in `run'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/lib/ruby/stdlib/rubygems/gem_runner.rb:55:in `run'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/bin/jgem:21:in `<main>'
	org/jruby/RubyKernel.java:979:in `load'
	/Users/ddinh/.rbenv/versions/jruby-9.1.7.0/bin/gem:4:in `<main>'
```

Is the issue with ruby

**Comment by dqdinh** [comment]
It seems from this issue (https://github.com/takari/ruby-maven/issues/5#issuecomment-263168168) there is support for jruby-9.1.6.0.

**Comment by dqdinh** [comment]
Actually, this works on jruby-9.1.6.0.

@mkristian do you know why it breaks on jruby-9.1.7.0 ?

```
$ gem install fast-rsa-engine -v '0.3.2' --backtrace
  jar dependencies for fast-rsa-engine-0.3.2-java.gemspec . . .
      com.squareup.jnagmp:bouncycastle-rsa:1.0.1:compile
Successfully installed fast-rsa-engine-0.3.2-java
1 gem installed
```
