### ISSUE TITLE
jar-dependencies-0.1.15 appears to be required for successful install of fast-rsa-engine 0.1.0

### ISSUE THREAD

**Issue by blaines** [lookout/fast-rsa-engine#9]
Just tried to do a simple `gem install` but was getting an error.

```
1.7.19@fast-rsa master ~/···/lookout/fast-rsa-engine> ruby --version
jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.8.0_05-b13 +jit [darwin-x86_64]
```

Here's the message I was receiving:
```
1.7.19@fast-rsa master ~/···/lookout/fast-rsa-engine> gem install fast-rsa-engine
Fetching: fast-rsa-engine-0.1.0-java.gem (100%)
  jar dependencies for fast-rsa-engine-0.1.0-java.gemspec . . .
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/maven/cli/MavenCli : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:254)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at org.codehaus.plexus.classworlds.launcher.Launcher.getMainClass(Launcher.java:144)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:266)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory - /Users/bschanfeldt/.rvm/gems/jruby-1.7.19@fast-rsa/gems/fast-rsa-engine-0.1.0-java/deps.lst
```

After installing `jar-dependencies-0.1.15` the same `gem install` works.

```
1.7.19@fast-rsa master ~/···/lookout/fast-rsa-engine> gem install fast-rsa-engine
Fetching: fast-rsa-engine-0.1.0-java.gem (100%)
Successfully installed fast-rsa-engine-0.1.0-java
1 gem installed
```

**Comment by rtyler** [comment]
@blaines there's also some issues with the utilization of fast-rsa-engine on older versions of JRuby like 1.7.19, which I believe has been fixed in the latest `HEAD`

**Comment by mkristian** [comment]
this is kind of weird since ```Unsupported major.minor version 51.0``` means some spawning of ```java``` picks up a java6

not sure why installing jar-dependencies ahead should/could help. let's if I can reproduce this somehow

**Comment by blaines** [comment]
I don't think I have a java6 but maybe I don't know everything that is installed...
```
1.7.18 master ~> ls -al /Library/Java/JavaVirtualMachines/jdk1.
jdk1.7.0_45.jdk/ jdk1.7.0_51.jdk/ jdk1.8.0_05.jdk/
```

**Comment by rtyler** [comment]
@blaines Apple ships by default with a JDK6 compatible JVM (IIRC), so perhaps the system Java is being used somehow
